import { db, auth } from './firebase-config.js';
import { GoogleAuthProvider, RecaptchaVerifier, signInWithPopup, signInWithEmailAndPassword, createUserWithEmailAndPassword, sendPasswordResetEmail, signInWithPhoneNumber, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/11.6.1/firebase-auth.js';
import { doc, getDoc, setDoc, updateDoc, collection, getDocs, addDoc, deleteDoc, query, where, orderBy, serverTimestamp } from 'https://www.gstatic.com/firebasejs/11.6.1/firebase-firestore.js';

const $ = id => document.getElementById(id); let confirmationResult; let appVerifier;
const message = (text, error=false) => { const el = $('account-view').hidden ? $('auth-message') : $('account-message'); el.textContent=text; el.className=`message${error?' error':''}`; };
async function removeAnonymous(){ if(auth.currentUser?.isAnonymous) await signOut(auth); }
async function ensureProfile(user){ const ref=doc(db,'users',user.uid), snap=await getDoc(ref); if(!snap.exists()) await setDoc(ref,{displayName:user.displayName||'',email:user.email||'',phoneNumber:user.phoneNumber||'',createdAt:serverTimestamp(),updatedAt:serverTimestamp()}); }
async function renderAccount(user){ await ensureProfile(user); const data=(await getDoc(doc(db,'users',user.uid))).data()||{}; $('profile-name').value=data.displayName||user.displayName||''; $('profile-phone').value=data.phoneNumber||user.phoneNumber||''; $('profile-email').value=data.email||user.email||''; $('account-email').textContent=user.email||user.phoneNumber||'Signed in'; await loadAddresses(user.uid); await loadOrders(user.uid); }
async function loadAddresses(uid){ const snap=await getDocs(collection(db,'users',uid,'addresses')); const list=$('addresses-list'); list.innerHTML=snap.empty?'<p>No saved addresses.</p>':''; snap.forEach(d=>{const a=d.data(); const el=document.createElement('article'); el.className='address-card'; el.innerHTML=`<strong>${escapeHtml(a.label||'Address')}</strong>${a.isDefault?'<span class="default-badge">Default</span>':''}<p>${escapeHtml(a.recipientName)}<br>${escapeHtml(a.line)}<br>${escapeHtml(a.city)}, ${escapeHtml(a.state)} - ${escapeHtml(a.pincode)}<br>${escapeHtml(a.phoneNumber)}</p><div class="address-actions"><button data-edit="${d.id}">Edit</button><button data-delete="${d.id}">Delete</button></div>`; el.querySelector('[data-edit]').onclick=()=>editAddress(d.id,a); el.querySelector('[data-delete]').onclick=async()=>{if(confirm('Delete this address?')){await deleteDoc(doc(db,'users',uid,'addresses',d.id));await loadAddresses(uid);}};list.append(el);}); }
function editAddress(id,a){$('address-form-wrap').hidden=false;$('address-id').value=id;$('address-label').value=a.label||'';$('address-name').value=a.recipientName||'';$('address-phone').value=a.phoneNumber||'';$('address-line').value=a.line||'';$('address-city').value=a.city||'';$('address-state').value=a.state||'';$('address-pincode').value=a.pincode||'';$('address-default').checked=!!a.isDefault;window.scrollTo({top:$('address-form-wrap').offsetTop-100,behavior:'smooth'});}
async function loadOrders(uid){ const list=$('orders-list'); try{const snap=await getDocs(query(collection(db,'orders'),where('userId','==',uid)));list.innerHTML=snap.empty?'<p>No orders yet.</p>':'';snap.docs.sort((a,b)=>(b.data().createdAt?.seconds||0)-(a.data().createdAt?.seconds||0)).forEach(d=>{const o=d.data(), date=o.createdAt?.toDate?.().toLocaleDateString()||'New';list.innerHTML+=`<article class="order-card"><strong>Order #${d.id.slice(-6).toUpperCase()}</strong><span class="status-badge">${escapeHtml(o.orderStatus||'Pending')}</span><p>${date} · ${o.items?.length||0} item(s) · ₹${Number(o.total||0).toFixed(2)}</p></article>`;});}catch(e){list.innerHTML='<p>Unable to load orders right now.</p>';}}
function escapeHtml(v=''){const d=document.createElement('div');d.textContent=v;return d.innerHTML;}
$('google-login').onclick=async()=>{try{await removeAnonymous();await signInWithPopup(auth,new GoogleAuthProvider());}catch(e){message(e.message,true);}};
$('email-form').onsubmit=async e=>{e.preventDefault();const email=$('auth-email').value,password=$('auth-password').value,name=$('auth-name').value.trim();try{await removeAnonymous();let result;try{result=await signInWithEmailAndPassword(auth,email,password);}catch(err){if(err.code!=='auth/invalid-credential'&&err.code!=='auth/user-not-found')throw err;result=await createUserWithEmailAndPassword(auth,email,password);await setDoc(doc(db,'users',result.user.uid),{displayName:name||'',email,phoneNumber:'',createdAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});}}catch(err){message(err.message,true);}};
$('forgot-password').onclick=async()=>{const email=$('auth-email').value.trim();if(!email)return message('Enter your email address first.',true);try{await sendPasswordResetEmail(auth,email);message('Password reset link sent to your email.');}catch(e){message(e.message,true);}};
$('phone-form').onsubmit=async e=>{e.preventDefault();try{await removeAnonymous();if(!appVerifier)appVerifier=new RecaptchaVerifier(auth,'recaptcha-container',{size:'invisible'});confirmationResult=await signInWithPhoneNumber(auth,$('phone-number').value.trim(),appVerifier);$('otp-form').hidden=false;message('OTP sent to your mobile number.');}catch(err){message(err.message,true);appVerifier?.clear();appVerifier=null;}};
$('otp-form').onsubmit=async e=>{e.preventDefault();try{await confirmationResult.confirm($('otp-code').value.trim());}catch(err){message('Invalid OTP. Please try again.',true);}};
$('profile-form').onsubmit=async e=>{e.preventDefault();try{await updateDoc(doc(db,'users',auth.currentUser.uid),{displayName:$('profile-name').value.trim(),updatedAt:serverTimestamp()});message('Profile saved.');}catch(err){message(err.message,true);}};
$('new-address').onclick=()=>{$('address-form').reset();$('address-id').value='';$('address-form-wrap').hidden=!$('address-form-wrap').hidden;};
$('address-form').onsubmit=async e=>{e.preventDefault();try{const uid=auth.currentUser.uid, isDefault=$('address-default').checked, data={label:$('address-label').value.trim(),recipientName:$('address-name').value.trim(),phoneNumber:$('address-phone').value.trim(),line:$('address-line').value.trim(),city:$('address-city').value.trim(),state:$('address-state').value.trim(),pincode:$('address-pincode').value.trim(),isDefault,updatedAt:serverTimestamp()};if(isDefault){const old=await getDocs(collection(db,'users',uid,'addresses'));await Promise.all(old.docs.map(x=>updateDoc(x.ref,{isDefault:false})));}const id=$('address-id').value;if(id)await updateDoc(doc(db,'users',uid,'addresses',id),data);else await addDoc(collection(db,'users',uid,'addresses'),{...data,createdAt:serverTimestamp()});$('address-form').reset();$('address-form-wrap').hidden=true;await loadAddresses(uid);message('Address saved.');}catch(err){message(err.message,true);}};
$('logout').onclick=()=>signOut(auth);
onAuthStateChanged(auth,async user=>{const active=user&&!user.isAnonymous;$('auth-view').hidden=!!active;$('account-view').hidden=!active;if(active)try{await renderAccount(user);}catch(e){message(e.message,true);}});
