import { db, auth } from './firebase-config.js';
import { GoogleAuthProvider, signInWithPopup, signInWithEmailAndPassword, createUserWithEmailAndPassword, sendPasswordResetEmail, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/11.6.1/firebase-auth.js';
import { doc, getDoc, setDoc, updateDoc, collection, getDocs, addDoc, deleteDoc, query, where, serverTimestamp } from 'https://www.gstatic.com/firebasejs/11.6.1/firebase-firestore.js';
const $=id=>document.getElementById(id); const panelIds=['profile-panel','address-panel','orders-panel','security-panel'];
const showMessage=(text,error=false,authMessage=false)=>{const el=$(authMessage?'auth-message':'account-message');el.textContent=text;el.className=`message${error?' error':''}`;};
const escapeHtml=(value='')=>{const el=document.createElement('div');el.textContent=value;return el.innerHTML;};
async function removeAnonymous(){if(auth.currentUser?.isAnonymous) await signOut(auth);}
async function ensureProfile(user){const ref=doc(db,'users',user.uid),snap=await getDoc(ref);if(!snap.exists())await setDoc(ref,{displayName:user.displayName||'',email:user.email||'',phoneNumber:user.phoneNumber||'',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});}
function openPanel(id){panelIds.forEach(panel=>$(panel).hidden=panel!==id);if(id==='address-panel')loadAddresses(auth.currentUser.uid);if(id==='orders-panel')loadOrders(auth.currentUser.uid);window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'});}
async function renderAccount(user){await ensureProfile(user);const profile=(await getDoc(doc(db,'users',user.uid))).data()||{};const name=profile.displayName||user.displayName||'there';$('greeting').textContent=`Hey, ${name}`;$('account-contact').textContent=profile.email||user.email||profile.phoneNumber||user.phoneNumber||'';$('profile-name').value=name==='there'?'':name;$('profile-email').value=profile.email||user.email||'';$('profile-phone').value=profile.phoneNumber||user.phoneNumber||'';}
async function loadAddresses(uid){const snap=await getDocs(collection(db,'users',uid,'addresses'));const list=$('addresses-list');list.innerHTML=snap.empty?'<p class="muted">No saved addresses yet.</p>':'';snap.forEach(item=>{const a=item.data(),el=document.createElement('article');el.className='address-card';el.innerHTML=`<strong>${escapeHtml(a.label||'Address')}</strong>${a.isDefault?'<span class="default-badge">Default</span>':''}<p>${escapeHtml(a.recipientName)}<br>${escapeHtml(a.line)}<br>${escapeHtml(a.city)}, ${escapeHtml(a.state)} - ${escapeHtml(a.pincode)}<br>${escapeHtml(a.phoneNumber)}</p><div class="address-actions"><button data-edit="${item.id}">Edit</button><button data-delete="${item.id}">Delete</button></div>`;el.querySelector('[data-edit]').onclick=()=>editAddress(item.id,a);el.querySelector('[data-delete]').onclick=async()=>{if(confirm('Delete this address?')){await deleteDoc(item.ref);loadAddresses(uid);}};list.append(el);});}
function editAddress(id,a){$('address-form-wrap').hidden=false;$('address-id').value=id;$('address-label').value=a.label||'';$('address-name').value=a.recipientName||'';$('address-phone').value=a.phoneNumber||'';$('address-line').value=a.line||'';$('address-city').value=a.city||'';$('address-state').value=a.state||'';$('address-pincode').value=a.pincode||'';$('address-default').checked=!!a.isDefault;}
async function loadOrders(uid){const list=$('orders-list');try{const snap=await getDocs(query(collection(db,'orders'),where('userId','==',uid)));list.innerHTML=snap.empty?'<p class="muted">No orders yet.</p>':'';snap.docs.sort((a,b)=>(b.data().createdAt?.seconds||0)-(a.data().createdAt?.seconds||0)).forEach(item=>{const order=item.data(),date=order.createdAt?.toDate?.().toLocaleDateString()||'New';list.innerHTML+=`<article class="order-card"><strong>Order #${item.id.slice(-6).toUpperCase()}</strong><span class="status-badge">${escapeHtml(order.orderStatus||'Pending')}</span><p>${date} · ${order.items?.length||0} item(s) · ₹${Number(order.total||0).toFixed(2)}</p></article>`;});}catch(error){list.innerHTML='<p class="muted">Unable to load orders right now.</p>';}}
function showAuth(mode='login'){$('auth-modal').hidden=false;$('login-form-view').hidden=mode!=='login';$('signup-form-view').hidden=mode!=='signup';$('auth-message').textContent='';}
$('open-login').onclick=()=>showAuth();$('close-auth').onclick=()=>$('auth-modal').hidden=true;$('auth-modal').onclick=event=>{if(event.target===$('auth-modal'))$('auth-modal').hidden=true;};$('show-signup').onclick=()=>showAuth('signup');$('show-login').onclick=()=>showAuth('login');
async function googleAuth(){try{await removeAnonymous();await signInWithPopup(auth,new GoogleAuthProvider());$('auth-modal').hidden=true;}catch(error){showMessage(error.message,true,true);}}
$('google-login').onclick=googleAuth;$('google-signup').onclick=googleAuth;
$('login-form').onsubmit=async event=>{event.preventDefault();try{await removeAnonymous();await signInWithEmailAndPassword(auth,$('login-email').value.trim(),$('login-password').value);$('auth-modal').hidden=true;}catch(error){showMessage('Email or password is incorrect.',true,true);}};
$('signup-form').onsubmit=async event=>{event.preventDefault();try{await removeAnonymous();const email=$('signup-email').value.trim(),result=await createUserWithEmailAndPassword(auth,email,$('signup-password').value);await setDoc(doc(db,'users',result.user.uid),{displayName:$('signup-name').value.trim(),email,phoneNumber:$('signup-phone').value.trim(),createdAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});$('auth-modal').hidden=true;}catch(error){showMessage(error.message,true,true);}};
$('forgot-password').onclick=async()=>{const email=$('login-email').value.trim();if(!email)return showMessage('Enter your registered email address first.',true,true);try{await sendPasswordResetEmail(auth,email);showMessage('Password reset link sent to your email.',false,true);}catch(error){showMessage(error.message,true,true);}};
document.querySelectorAll('[data-panel]').forEach(button=>button.onclick=()=>openPanel(button.dataset.panel));document.querySelectorAll('.close-panel').forEach(button=>button.onclick=()=>panelIds.forEach(id=>$(id).hidden=true));
$('profile-form').onsubmit=async event=>{event.preventDefault();try{await updateDoc(doc(db,'users',auth.currentUser.uid),{displayName:$('profile-name').value.trim(),updatedAt:serverTimestamp()});await renderAccount(auth.currentUser);showMessage('Profile updated.');}catch(error){showMessage(error.message,true);}};
$('new-address').onclick=()=>{$('address-form').reset();$('address-id').value='';$('address-form-wrap').hidden=!$('address-form-wrap').hidden;};
$('address-form').onsubmit=async event=>{event.preventDefault();try{const uid=auth.currentUser.uid,defaultAddress=$('address-default').checked,data={label:$('address-label').value.trim(),recipientName:$('address-name').value.trim(),phoneNumber:$('address-phone').value.trim(),line:$('address-line').value.trim(),city:$('address-city').value.trim(),state:$('address-state').value.trim(),pincode:$('address-pincode').value.trim(),isDefault:defaultAddress,updatedAt:serverTimestamp()};if(defaultAddress){const old=await getDocs(collection(db,'users',uid,'addresses'));await Promise.all(old.docs.map(item=>updateDoc(item.ref,{isDefault:false})));}const id=$('address-id').value;if(id)await updateDoc(doc(db,'users',uid,'addresses',id),data);else await addDoc(collection(db,'users',uid,'addresses'),{...data,createdAt:serverTimestamp()});$('address-form').reset();$('address-form-wrap').hidden=true;loadAddresses(uid);showMessage('Address saved.');}catch(error){showMessage(error.message,true);}};
$('send-reset').onclick=async()=>{const email=auth.currentUser?.email;if(!email)return showMessage('Password reset is available for email accounts only.',true);try{await sendPasswordResetEmail(auth,email);showMessage('Password reset link sent to your email.');}catch(error){showMessage(error.message,true);}};
$('theme-toggle').onclick=()=>{document.body.classList.toggle('light-mode');localStorage.setItem('app-theme',document.body.classList.contains('light-mode')?'light':'dark');$('theme-toggle').textContent=document.body.classList.contains('light-mode')?'☀':'☾';};$('logout').onclick=()=>signOut(auth);
onAuthStateChanged(auth,async user=>{const active=user&&!user.isAnonymous;$('guest-view').hidden=!!active;$('account-view').hidden=!active;if(active){$('auth-modal').hidden=true;try{await renderAccount(user);}catch(error){showMessage(error.message,true);}}});
